### ISSUE TITLE
Add gzip compression

### ISSUE THREAD

**Issue by adranwit** [parsyl/parquet#12]
The current implementation misses gzip compression

**Comment by cswank** [comment]
@adranwit I just opened a PR for this, but the gzip unit tests very slow, so I'd like to find out why before merging.

https://github.com/parsyl/parquet/pull/13

**Comment by cswank** [comment]
Oh wow, you made some huge changes in your fork, I'd be interested to hear how that fork is working out.

**Comment by adranwit** [comment]
Thanks, for picking up PR, like your initial approach, (low memory consumption and reasonable speed)
We're using parquet to load data to BQ, 
sadly the original library has issues and is incompatible with Parque spec (version 1), and nested repeated fields do not work in 2 levels down.

I this point I got it working to load data to BQ, reading code generation still has some issue.

I haven't heard from you for some time, so I've rewritten code generation, and patched various issue, 
I plan to rewrite it at some, point from "scratch", leaving some abstraction, adding more features like a dictionary. 

https://github.com/viant/parquet

**Comment by cswank** [comment]
I'm not surprised that our lib has issues like you found, since I started with zero parquet knowledge when I worked on this.  Parquet has so many options and I found it really hard to get everything right.

It is working fine for our use case (no nesting in AWS Glue) so we rarely have had to touch it since I wrote it 2 years ago.

Anyhow, your fork is obviously way out of sync with our version, but I'd be interested in some kind of collaboration.  I'd even consider adapting the work you've done in your fork since you've been able to fix some issues with our version.  One thing I'm kind of surprised about, though, is that your fork dropped the unit tests at the root of the repo.  I found those absolutely invaluable.  They are how I was able to get gzip working in just one morning.  I made the same mistake your fork did (not reading CompressedPageSize into the gzip reader) and the tests helped me find that.

Also, I've been wanting to try my hand at dictionary encoding for a while, but I have been unable to figure out how that works.  The documentation is sparse and all the other implementations are really hard to read.

Anyhow, I'd be totally down for merging your work into our repo if it is more correct than our version.
